app_name: mt

server:
  port: 50305

mid_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50302
  timeout: 10

service:
  queues:
    pixels: pixels
    db_actions: mt_manager
    transaction_log: transaction_log
    restore_pixels: restore_pixels
    reporter_transaction: reporter_transaction

  mobilink:
    enabled: false

  yondu:
    enabled: false
  
  cheese:
    enabled: true
    operator_name: cheese
    country_code: 66
    mcc: 520
    dtac_mnc: 05
    ais_mnc: 01
    trueh_mnc: 03
    new:
      name: cheese_mo
      enabled: true
      prefetch_count: 10
      threads_count: 10

  qrtech:
    enabled: false

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_cheese
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit-prod.ceta2yrq1zco.ap-southeast-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10

publisher:
  chan_capacity: 2000
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
