app_name: mt_manager

server:
  port: 50305

inmem_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50302
  timeout: 10

service:
  queues:
    pixels: pixels
    db_actions: mt_manager
    transaction_log: transaction_log

  mobilink:
    enabled: false

  yondu:
    enabled: false
    operator_name: yondu
    operator_code: 51501
    country_code: 515
    charge_on_rejected: true
    location: Asia/Bangkok
    content:
      send_enabled: false
      url: http://dev.pk.linkit360.ru/u/
    texts:
      rejected: "You already subscribed on this service."
      rejected_charge: "You already subscribed on this service. Please find more games here: %s"
      blacklisted: "Sorry, service not available."
      postpaid: "Sorry, service not available."
      unsubscribe: "You have been unsubscribed."
  
  cheese:
    enabled: true
    operator_name: cheese
    country_code: 66
    mcc: 520
    dtac_mnc: 05
    ais_mnc: 01
    trueh_mnc: 03
    new:
      name: cheese_mo
      enabled: true
      prefetch_count: 10
      threads_count: 10

  qrtech:
    enabled: false

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_cheese
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit-prod.ceta2yrq1zco.ap-southeast-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10

publisher:
  pending_buffer_path: /home/centos/linkit/mt_manager_pending.json
  chan_capacity: 2000
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
