app_name: telco

server:
  port: 50306
  threads_count: 1


beeline:
  name: beeline
  transaction_log:
    response: /var/log/linkit/response_beeline.log
    request: /var/log/linkit/requests_beeline.log
  queues:
    smpp: beeline_smpp 
  smpp:
    addr: 217.118.84.12:3340
    user: 1637571
    pass: wBy4E2Tz
    timeout: 10
    reconnect_delay: 10   


consumer:
  reconnect_delay: 10
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672

publisher:
  chan_capacity: 100
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672

