app_name: mid

server:
  rpc_port: 50307
  http_port: 50308

xmp_api:
  enabled: true
  dsn: 54.254.222.204:50318
  timeout: 10
  instance_id: 967eda58-0e47-4bd4-8128-b30461eb9b19

aws:
  region: ap-southeast-1
  access_key_id: AKIAJNOENJABOE62GPYQ
  secret_access_key: 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
  download_timeout: 2m

service:
  state_file_path: /home/centos/linkit/mid.state.json
  unique_days: 10
  static_path: /var/www/xmp.linkit360.ru/web/
  queue:
    reporter_hit:
      enabled: true
      name: reporter_hit
      prefetch_count: 10
      threads_count: 10

    reporter_transaction:
      enabled: true
      name: reporter_transaction
      prefetch_count: 10
      threads_count: 10

    reporter_outflow:
      enabled: true
      name: reporter_outflow
      prefetch_count: 10
      threads_count: 10

    reporter_pixel:
      enabled: true
      name: reporter_pixel
      prefetch_count: 10
      threads_count: 10

  service:
    from_control_panel: false

  campaign:
    from_control_panel: false
    webhook: http://localhost:50300/updateTemplates
    landing_path: /var/www/xmp.linkit360.ru/web/campaign/
    bucket: xmp-lp
    download_timeout: 10m

  content:
    from_control_panel: false
    content_path: /var/www/xmp.linkit360.ru/web/uploaded_content/
    region: ap-southeast-1
    bucket: xmp-content
    download_timeout: 10m

  blacklist:
    from_control_panel: false
    bucket: xmp-blacklist
    zip_temp_dir: /var/www/xmp.linkit360.ru/blacklist/

  pixel:
    from_control_panel: false

  operator:
    from_control_panel: false

  enabled:
    services: true
    campaigns: true
    blacklist: true
    operators: true
    contents: true
    blacklist: false
    pixel_settings: false
    reporter: true
    destinations: false
    redirect_stats_count: false

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_beeline
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
