app_name: mt

server:
  port: 50305

mid_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50302
  timeout: 10

service:
  queues:
    pixels: pixels
    db_actions: mt_manager
    transaction_log: transaction_log
    restore_pixels: restore_pixels
    reporter_transaction: reporter_transaction

  beeline:
    enabled: true
    operator_name: beeline
    mccmnc: 25099
    country_code: 7
    new:
      name: beeline_mo
      enabled: true
      prefetch_count: 10
      threads_count: 10
    smpp:
      name: beeline_smpp
      prefetch_count: 10
      enabled: true
      threads_count: 10
  
db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_beeline
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10

publisher:
  chan_capacity: 100
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
