app_name: contentd

server:
  rpc_port: 50301
  http_port: 50302

mid_client:
  dsn: :50307
  timeout: 10

service:
  retry_count: 10
  unique_urls_salt: !&5x~_~R_-9Uri
  queues:
    unique_urls: unique_urls

inmem_client:
  dsn: :50307
  timeout: 10

notifier:
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
  reconnect_delay: 10
  chan_capacity: 10000
