app_name: dispatcherd


server: 
  port: 50300
  url: http://platform.pk.linkit360.ru
  path: /var/www/xmp.linkit360.ru/web/

  sessions:
    secret: rCs7h2h_NqB5Kx-
    path: /
    domain: platform.pk.linkit360.ru
    cookie_ttl: 300
    secure: false
    http_only: false 
    key: sehB33772

service:
  # error_redirect_url: http://pk.linkit360.ru/cpa.k.ak100
  error_redirect_url: http://id.slypee.com
  not_found_redirect_url: http://platform.pk.linkit360.ru/lp/cpa.k.ak100
  campaign_hash_length: 32
  redirect_on_gather_error: true
  start_new_subscription_on_click: true
  rejected:
    campaign_redirect_enabled: false
    traffic_redirect_enabled: true
  landings:
    beeline:
      enabled: false
      url: http://217.118.84.12:8888/CDP_WapTester/emulator
      timeout: 30
      user: 1637572
      pass: KhZbQo1n

notifier:
  queues:
    access_campaign: access_campaign
    user_actions: user_actions
    content_sent: content_sent
    traffic_redirects: traffic_redirects

  rbmq:
    conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
    chan_capacity: 10000
    pending_buffer_path: /home/centos/linkit/dispatcherd_pending.json

