app_name: dispatcherd

server: 
  port: 50300
  url: http://platform.pk.linkit360.ru
  path: /var/www/xmp.linkit360.ru/web/

  sessions:
    secret: rCs7h2h_NqB5Kx-
    path: /
    domain: platform.pk.linkit360.ru
    cookie_ttl: 1036800
    secure: false
    http_only: false 
    key: sehB33772

mid_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50301
  timeout: 10

redirect_client:
  dsn: :50312
  timeout: 10

service:
  campaign_hash_length: 32
  error_redirect_url: http://id.slypee.com
  not_found_redirect_url: http://platform.pk.linkit360.ru/lp/cpa.k.ak0/
  redirect_on_gather_error: true
  start_new_subscription_on_click: true
  content_service_code_default: 23
  content_campaign_code_default: 290
  operator_code: 41001
  country_code: 92
  rejected:
    campaign_redirect_enabled: false
    traffic_redirect_enabled: false

  landings:
    custom: true
    mobilink:
      enabled: true
      queues:
        responses: mobilink_responses
        mo: mobilink_new_subscriptions
      cache:
        expiration_hours: 24
        cleanup_interval: 1
        file_path: /home/centos/linkit/dispatcher.cache  

notifier:
  queues:
    access_campaign: access_campaign
    user_actions: user_actions
    content_sent: content_sent
    pixel_sent: pixel_sent
    traffic_redirects: traffic_redirects

  rbmq:
    conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
    chan_capacity: 10000
