app_name: inmem
server:
  rpc_port: 50307
  http_port: 50308

service:
  provider_name: mobilink
  unique_days: 10
  operator_code: 41001
  static_path: /var/www/xmp.linkit360.ru/web/
  redirect_url: http://id.slypee.com

  enabled:
    destinations: true
    redirect_stats_count: true

  private_networks:
  - start: 10.0.0.0
    end: 10.255.255.255
  - start: 100.64.0.0
    end: 100.127.255.255
  - start: 172.16.0.0
    end: 172.31.255.255
  - start: 192.0.0.0
    end: 192.0.0.255
  - start: 192.168.0.0
    end: 192.168.255.255
  - start: 198.18.0.0
    end: 198.19.255.255

db:
  conn_ttl: -1
  max_conns: 15
  timeout: 30
  name: linkit_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: linkit-mobilink.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_
