app_name: jobs

server:
  port: 50303

jobs:
  planned_enabled: false
  injections_path: /var/www/xmp.linkit360.ru/web/injections
  check_prefix: 92
  callback_url: http://xmp.linkit360.ru/injection-jobs/callback
  log_path: /var/log/linkit/

metrics:
  allowed_db_size: 1080018382100
  db:
  - linkit_mobilink
  - pk_mobilink

inmem_client:
  timeout: 10

publisher:
  chan_capacity: 100
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672

db:
  conn_ttl: -1
  max_open_conns: 10
  max_idle_conns: 10
  timeout: 30
  name: pk_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: linkit-mobilink.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

db_slave:
  conn_ttl: -1
  max_open_conns: 10
  max_idle_conns: 10
  timeout: 30
  name: pk_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: mobilink-slave-1.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_
