app_name: mid

server:
  rpc_port: 50307
  http_port: 50308

xmp_api:
  enabled: true
  dsn: 52.220.50.252:50318
  timeout: 10
  instance_id: 58fbedf7-1abc-402b-8c2a-89fe256d32d9

service:
  state_file_path: /home/centos/linkit/mid.state.json
  unique_days: 10
  operator_code: 41001
  static_path: /var/www/xmp.linkit360.ru/web/

  queue:
    reporter_hit:
      enabled: true
      name: reporter_hit
      prefetch_count: 10
      threads_count: 10

    reporter_transaction:
      enabled: true
      name: reporter_transaction
      prefetch_count: 10
      threads_count: 10

    reporter_outflow:
      enabled: true
      name: reporter_outflow
      prefetch_count: 10
      threads_count: 10

    reporter_pixel:
      enabled: true
      name: reporter_pixel
      prefetch_count: 10
      threads_count: 10

  service:
    from_control_panel: false

  campaign:
    from_control_panel: false
    webhook: http://localhost:50300/updateTemplates
    landing_path: /var/www/xmp.linkit360.ru/web/
    region: ap-southeast-1
    bucket: xmp-lp
    download_timeout: 10m

  content:
    enabled: true
    from_control_panel: false
    content_path: /var/www/xmp.linkit360.ru/web/
    region: ap-southeast-1
    bucket: xmp-content
    download_timeout: 10m

  blacklist:
    from_control_panel: false

  content:
    from_control_panel: false

  pixel:
    from_control_panel: false

  operator:
    from_control_panel: false

  enabled:
    reporter: true
    destinations: false
    redirect_stats_count: false

  private_networks:
  - start: 10.0.0.0
    end: 10.255.255.255
  - start: 100.64.0.0
    end: 100.127.255.255
  - start: 172.16.0.0
    end: 172.31.255.255
  - start: 192.0.0.0
    end: 192.0.0.255
  - start: 192.168.0.0
    end: 192.168.255.255
  - start: 198.18.0.0
    end: 198.19.255.255

db:
  conn_ttl: -1
  max_conns: 15
  timeout: 30
  name: pk_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: linkit-mobilink.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10w
