app_name: mt

server:
  port: 50305

inmem_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50302
  timeout: 10

reporter_client:
  dsn: :50315
  timeout: 10

service:
  queues:
    pixels: pixels
    db_actions: mt_manager
    transaction_log: transaction_log
    restore_pixels: restore_pixels

  mobilink:
    enabled: true
    operator_name: mobilink
    operator_code: 41001
    rejected_hours: 720

    channel:
      enabled: true
      url: http://pk2.slypee.com/support/notify.php

    periodic:
      enabled: true
      period: 3600
      fetch_limit: 10

    content:
      enabled: true
      fetch_period_seconds: 3600
      fetch_limit: 1

    new:
      name: mobilink_new_subscriptions
      enabled: true
      prefetch_count: 100
      threads_count: 10
    mo:
      name: mobilink_mo_tarifficate
      enabled: true
      prefetch_count: 100
      threads_count: 10
    sms: mobilink_sms_requests
    charge_req: mobilink_requests

    charge_resp:
      name: mobilink_responses
      enabled: true
      prefetch_count: 100
      threads_count: 10

  yondu:
    enabled: false
    operator_name: yondu
    operator_code: 51501
    content_url: http://dev.pk.linkit360.ru/u/
    charge_on_rejected: true
    texts:
      rejected: "You already subscribed on this service."
      rejected_charge: "You already subscribed on this service. Please find more games here: %s"
      blacklisted: "Sorry, service not available."
      postpaid: "Sorry, service not available."
      unsubscribe: "You have been unsubscribed."
    periodic:
      enabled: false
      fetch_limit: 10

  cheese:
    enabled: false

db:
  conn_ttl: -1
  max_open_conns: 35
  max_idle_conns: 35
  timeout: 30
  name: pk_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: linkit-mobilink.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10

publisher:
  chan_capacity: 100000
  rbmq:
    conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
