app_name: mt

server:
  port: 50305

mid_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50302
  timeout: 10

service:
  queues:
    pixels: pixels
    db_actions: mt_manager
    transaction_log: transaction_log
    restore_pixels: restore_pixels
    reporter_transaction: reporter_transaction

  mobilink:
    enabled: true
    operator_name: mobilink
    operator_code: 41001
    rejected_hours: 720

    channel:
      enabled: true
      url: http://pk2.slypee.com/support/notify.php

    periodic:
      enabled: true
      period: 3600
      fetch_limit: 100

    recharge:
      enabled: true
      fetch_limit: 10
      fetch_limit: 100

    content:
      enabled: true
      fetch_period_seconds: 3600
      fetch_limit: 100
      url: http://platform.pk.linkit360.ru/u/

    new:
      name: mobilink_new_subscriptions
      enabled: true
      prefetch_count: 100
      threads_count: 10
    mo:
      name: mobilink_mo_tarifficate
      enabled: true
      prefetch_count: 100
      threads_count: 10

    sms: mobilink_sms_requests
    charge_req: mobilink_requests

    charge_resp:
      name: mobilink_responses
      enabled: true
      prefetch_count: 100
      threads_count: 10

db:
  conn_ttl: -1
  max_open_conns: 35
  max_idle_conns: 35
  timeout: 30
  name: pk_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: linkit-mobilink.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10

publisher:
  chan_capacity: 1000
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
