app_name: dispatcherd

server:
  port: 50300
  path: /var/www/xmp.linkit360.ru/web/
  url: http://platform.ph.linkit360.ru

  sessions:
    secret: rCs7h2h_NqB5Kx-
    path: /
    domain: platform.ph.linkit360.ru
    cookie_ttl: 3600
    secure: false
    http_only: false

mid_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50301
  timeout: 10

service:
  error_redirect_url: http://id.slypee.com
  not_found_redirect_url: http://id.slypee.com
  send_restore_pixel_enabled: true
  start_new_subscription_on_click: false
  campaign_hash_length: 32
  redirect_on_gather_error: false 
  rejected:
    campaign_redirect_enabled: false
    traffic_redirect_enabled: false

notifier:
  queues:
    access_campaign: access_campaign
    user_actions: user_actions
    content_sent: content_sent
    pixel_sent: pixel_sent
    traffic_redirects: traffic_redirects

  rbmq:
    conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
    chan_capacity: 100
