app_name: mt_manager

server:
  port: 50305

service:
  queues:
    pixels: pixels
    db_actions: mt_manager
    transaction_log: transaction_log

  mobilink:
    enabled: false

  yondu:
    enabled: true
    operator_name: yondu
    operator_code: 51501
    country_code: 515
    charge_on_rejected: true
    content:
      send_enabled: false
      url: http://platform.ph.linkit360.ru/u/
    texts:
      rejected: "You already subscribed on this service."
      rejected_charge: "You already subscribed on this service. Please find more games here: %s"
      blacklisted: "Sorry, service not available."
      postpaid: "Sorry, service not available."
      unsubscribe: "You have been unsubscribed."
    periodic:
      enabled: true
      fetch_limit: 10
    subscription:
      enabled: true
      delay_minutes: 1
      fetch_limit: 200
      priority: 0
    retries:
      enabled: false
      period: 500
      fetch_limit: 100
      check_queues_free:
      - "yondu_charge"
      - "mt_manager"
      queue_free_size: 2500
    unsubscribe:
      - off
    consent:
     enabled: false
     queue: yondu_consent
     repeat:
       enabled: true
       delay_minutes: 10
       fetch_limit: 40
    mt: yondu_mt
    charge: yondu_charge
    new:
      name: yondu_mo
      enabled: true
      prefetch_count: 10
      threads_count: 10
    callback:
      name: yondu_callback
      prefetch_count: 10
      enabled: true
      threads_count: 10

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_yondu
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit-prod.ceta2yrq1zco.ap-southeast-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10

publisher:
  pending_buffer_path: /home/centos/linkit/mt_manager_pending.json
  chan_capacity: 1200
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
