app_name: mt_manager

server:
  port: 50305

inmem_client:
  dsn: :50307
  timeout: 10

content_client:
  dsn: :50302
  timeout: 10

service:
  queues:
    pixels: pixels
    db_actions: mt_manager
    transaction_log: transaction_log

  mobilink:
    enabled: false

  yondu:
    enabled: true
    operator_name: yondu
    operator_code: 51501
    country_code: 515
    charge_on_rejected: true
    location: Asia/Bangkok
    content:
      send_enabled: true
      url: http://platform.ph.linkit360.ru/u/
    texts:
      rejected: "You already subscribed on this service."
      rejected_charge: "You already subscribed on this service. Please find more games here: %s"
      blacklisted: "Sorry, service not available."
      postpaid: "Sorry, service not available."
      unsubscribe: "You have been unsubscribed."
    periodic:
      enabled: false
      fetch_limit: 10
      interval_type: min
      failed_repeat_in_minutes: 60
    unsubscribe:
      - off
    mt: yondu_mt
    mo:
      name: yondu_mo
      enabled: true
      prefetch_count: 10
      threads_count: 10
    dn:
      name: yondu_dn
      prefetch_count: 10
      enabled: true
      threads_count: 10
    dn_code:
      200: Success. Successfully charged
      201: Success. Successfully charged
      400: Authentication Error. Credentials error to telco
      401: Subscriber not found
      402: Subscriber mobile number is not active
      411: GHP Subscriber has insufficient balance Insufficient balance to all Prepaid/GHP subscribers
      412: EricssonInsuffBal.  Insufficient balance to all Touch Mobile subscribers
      414: StatusInactive. Postpaid subscriber is inactive
      416: ServerError. Current service is down or inactive
      500: ReadTimeout. Current service is down or inactive
      503: CSP Error. Telco problem to connect in CSP platform / App is not provisioned for charging or this rate / Charging amount is not provision / System is busy / Connection problem to telco
      1001: No Response. Cannot connect Telco API after 3 attempts
      1002: Connection Refused. Cannot access Telco API

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_yondu
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit-prod.ceta2yrq1zco.ap-southeast-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10

publisher:
  pending_buffer_path: /home/centos/linkit/mt_manager_pending.json
  chan_capacity: 1200
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
