app_name: pixels

server:
  port: 50309
  env: dev

service:
  queue:
    name: pixels
    prefetch_count: 10
    threads_count: 10

  delay: 1
  api:
    limit: 500
    hours: 0

inmem_client:
  port: 50307
  timeout: 10


notifier:
  queue:
    pixels: pixels
    pixel_sent: pixel_sent
  rbmq:
    conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
    chan_capacity: 10000
    pending_buffer_path: /home/centos/linkit/pixels_pending.json

consumer:
  reconnect_delay: 10
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672


db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_yondu
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit-prod.ceta2yrq1zco.ap-southeast-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_
