app_name: contentd

server:
  rpc_port: 50321
  http_port: 50322

mid_client:
  dsn: :50327
  timeout: 10

service:
  retry_count: 10
  queues:
    unique_urls: qrtech_unique_urls

notifier:
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672
  chan_capacity: 100
