app_name: dispatcherd

server:
  port: 50320
  path: /var/www/xmp.linkit360.ru/web/
  url: http://platform.th.linkit360.ru

  sessions:
    secret: rCs7h2h_NqB5Kx-
    path: /
    domain: platform.th.linkit360.ru
    cookie_ttl: 3600
    secure: false
    http_only: false

service:
  redirect_on_gather_error: false
  error_redirect_url: http://id.slypee.com
  campaign_hash_length: 32
  redirect_on_gather_error: false
  send_restore_pixel_enabled: true
  start_new_subscription_on_click: false
  rejected:
    campaign_redirect_enabled: false
    traffic_redirect_enabled: false
  landings:
    custom: true
    beeline:
      enabled: false
      url: http://217.118.84.12:8888/CDP_WapTester/emulator
      timeout: 30
      user: 1637572
      pass: KhZbQo1n
    qrtech:
      enabled: true
      content_url: http://platform.th.linkit360.ru/qr/get
      ais_url: http://wap.funspaz.com/wap/partner/linkit360/ais_wap.php
      dtac_url: http://wap.funspaz.com/wap/partner/linkit360/aoc_dtac.php 

inmem_client:
  dsn: :50327
  timeout: 10

content_client:
  dsn: :50321
  timeout: 10

redirect_client:
  dsn: :50332
  timeout: 10


notifier:
  queues:
    access_campaign: qrtech_access_campaign
    user_actions: qrtech_user_actions
    content_sent: qrtech_content_sent
    traffic_redirects: qrtech_traffic_redirects
    pixel_sent: qrtech_pixel_sent

  rbmq:
    conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
    chan_capacity: 100
    pending_buffer_path: /home/centos/linkit/dispatcherd_pending.json
