app_name: inmem

server:
  rpc_port: 50327
  http_port: 50328

service:
  provider_name: qrtech
  unique_days: 10
  static_path: /var/www/xmp.linkit360.ru/web/
  redirect_url: http://id.slypee.com
  campaign_web_hook: http://localhost:50320/updateTemplates

  private_networks:
  - start: 10.0.0.0
    end: 10.255.255.255
  - start: 100.64.0.0
    end: 100.127.255.255
  - start: 172.16.0.0
    end: 172.31.255.255
  - start: 192.0.0.0
    end: 192.0.0.255
  - start: 192.168.0.0
    end: 192.168.255.255
  - start: 198.18.0.0
    end: 198.19.255.255

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_qrtech
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit-prod.ceta2yrq1zco.ap-southeast-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_
