app_name: mid

server:
  rpc_port: 50327
  http_port: 50328

xmp_api:
  enabled: true
  dsn: 54.254.222.204:50318
  client_port: 50344
  timeout: 10
  instance_id: ecbe1211-3b1e-4c91-96fc-574dc979668a

aws:
  region: ap-southeast-1
  access_key_id: AKIAJNOENJABOE62GPYQ
  secret_access_key: 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
  download_timeout: 2m

service:
  state_file_path: /home/centos/qrtech/mid.state.json
  unique_days: 10
  static_path: /var/www/xmp.linkit360.ru/web/
  queue:
    reporter_hit:
      enabled: true
      name: qrtech_reporter_hit
      prefetch_count: 10
      threads_count: 10

    reporter_transaction:
      enabled: true
      name: qrtech_reporter_transaction
      prefetch_count: 10
      threads_count: 10

    reporter_outflow:
      enabled: true
      name: qrtech_reporter_outflow
      prefetch_count: 10
      threads_count: 10

    reporter_pixel:
      enabled: true
      name: qrtech_reporter_pixel
      prefetch_count: 10
      threads_count: 10

  
  service:
    from_control_panel: true

  campaign:
    from_control_panel: true
    landing_path: /var/www/xmp.linkit360.ru/web/campaign/
    bucket: xmp-lp
    webhook: http://localhost:50320/updateTemplates

  content:
    from_control_panel: true
    content_path: /var/www/xmp.linkit360.ru/web/uploaded_content/
    bucket: xmp-content

  blacklist:
    from_control_panel: false
    zip_temp_dir: /var/www/xmp.linkit360.ru/blacklist/
    bucket: xmp-blacklist

  pixel:
    from_control_panel: false

  operator:
    from_control_panel: true

  enabled:
    services: false
    campaigns: false
    blacklist: false
    operators: false
    contents: false
    pixel_settings: false
    reporter: true
    destinations: false
    redirect_stats_count: false


db:
  conn_ttl: -1
  max_open_conns: 8
  max_idle_conns: 5
  timeout: 30
  name: linkit_qrtech
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit-prod.ceta2yrq1zco.ap-southeast-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: localhost
      port: 5672
  binding_key: ""
  reconnect_delay: 10w
